name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.x

      - name: PNPM Install
        run: pnpm install

      - name: Check Version
        run: pnpm version:check

      - name: Build packages
        run: pnpm build

      - name: Publish to npm
        run: |
          pnpm --filter "./packages/*" publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}